=head1 NAME

Test::DBIC::Calls - test statistics about your DBIC calls

=head1 SYNOPSIS

Run a subtest with a debugging object (L<Test::DBIC::Profiler>) set to capture
the number of calls that have been made to the database. This may be useful to
check your assumptions about prefetching, etc.

    use Test::More;
    use Test::DBIC::Calls;

    # get a DBIC object, for example using Test::DBIx::Class
    use Test::DBIx::Class;
    my $db = Schema;

    with_stats 'test 1', $db, sub {
        my $stats = shift;

        my $rs = $db->resultset('Foo')->search();
        is $stats->call_count, 0, 'No calls on preparing RS';

        my @foo = $rs->all;
        is $stats->call_count, 1, '1 call after preparing RS';
    };

=head1 EXPORTED FUNCTIONS

=over 4

=item C<with_stats $name, $db, $code>

The L<Test::DBIC::Profiler> object is created for the database and is passed to
your code reference as its first and only argument.

=back


=cut

=head1 AUTHOR

osfameron <osfameron@cpan.org> 2014


=cut

